/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppGraph {
    }
    interface AppRoot {
    }
    interface AppSettings {
    }
    interface AppTimer {
        "isPaused": any;
    }
}
declare global {
    interface HTMLAppGraphElement extends Components.AppGraph, HTMLStencilElement {
    }
    var HTMLAppGraphElement: {
        prototype: HTMLAppGraphElement;
        new (): HTMLAppGraphElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSettingsElement extends Components.AppSettings, HTMLStencilElement {
    }
    var HTMLAppSettingsElement: {
        prototype: HTMLAppSettingsElement;
        new (): HTMLAppSettingsElement;
    };
    interface HTMLAppTimerElement extends Components.AppTimer, HTMLStencilElement {
    }
    var HTMLAppTimerElement: {
        prototype: HTMLAppTimerElement;
        new (): HTMLAppTimerElement;
    };
    interface HTMLElementTagNameMap {
        "app-graph": HTMLAppGraphElement;
        "app-root": HTMLAppRootElement;
        "app-settings": HTMLAppSettingsElement;
        "app-timer": HTMLAppTimerElement;
    }
}
declare namespace LocalJSX {
    interface AppGraph {
    }
    interface AppRoot {
    }
    interface AppSettings {
    }
    interface AppTimer {
        "isPaused"?: any;
    }
    interface IntrinsicElements {
        "app-graph": AppGraph;
        "app-root": AppRoot;
        "app-settings": AppSettings;
        "app-timer": AppTimer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-graph": LocalJSX.AppGraph & JSXBase.HTMLAttributes<HTMLAppGraphElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-settings": LocalJSX.AppSettings & JSXBase.HTMLAttributes<HTMLAppSettingsElement>;
            "app-timer": LocalJSX.AppTimer & JSXBase.HTMLAttributes<HTMLAppTimerElement>;
        }
    }
}
